-- Default keybindings for launching apps in Hyper Mode
--
-- To launch _your_ most commonly-used apps via Hyper Mode, create a copy of
-- this file, save it as `hyper-apps.lua`, and edit the table below to configure
-- your preferred shortcuts.
return {
  --[[A for App]]                              { 'a', 'App Store'},
  --[[B for Browser]]                          { 'b', 'Google Chrome'},
  --[[C for ]]                                 -- { 'c', ''},
  --[[D for ]]                                 -- { 'd', ''},
  --[[E for ]]                                 -- { 'e', ''},
  --[[F for Finder]]                           { 'f', 'Finder'},
  --[[G for ]]                                 -- { 'g', ''},
  --[[H for reload Hammerspoon config]]        { 'h', function() hs.reload() end},
  --[[I for ]]                                 -- { 'i', ''},
  --[[J for ]]                                 -- { 'j', ''},
  --[[K for ]]                                 -- { 'k', ''},
  --[[L for ]]                                 -- { 'l', ''},
  --[[M for ]]                                 -- { 'm', ''},
  --[[N for ]]                                 -- { 'n', ''},
  --[[O for ]]                                 -- { 'o', ''},
  --[[P for Preferences]]                      { 'p', 'System Preferences'},
  --[[Q for ]]                                 -- { 'q', ''},
  --[[R for ]]                                 -- { 'r', ''},
  --[[S for ]]                                 -- { 's', ''},
  --[[T for Terminal]]                         { 't', 'Terminal'},
  --[[U for ]]                                 -- { 'u', ''},
  --[[V for ]]                                 -- { 'v', ''},
  --[[W for Word]]                             { 'w', 'Microsoft Word'},
  --[[X for Xcode]]                            { 'x', 'Xcode'},
  --[[Y for ]]                                 -- { 'y', ''},
  --[[Z for ]]                                 -- { 'z', ''},
}
