-- Default keybindings for launching apps in Hyper Mode
--
-- To launch _your_ most commonly-used apps via Hyper Mode, create a copy of
-- this file, save it as `hyper-apps.lua`, and edit the table below to configure
-- your preferred shortcuts.
return {
  --[[A for App]]                              { 'a', 'App Store'},
  --[[B for Browser]]                          { 'b', 'Google Chrome'},
  --[[C for Chat]]                             { 'c', 'Messenger'},
  --[[D for Dash]]                             { 'd', 'Dash'},
  --[[E for Edge]]                             { 'e', 'Microsoft Edge'},
  --[[F for Finder]]                           { 'f', 'Finder'},
  --[[G for GraphiQL]]                         { 'g', 'GraphiQL'},
  --[[H for reload Hammerspoon config]]        { 'h', function() hs.reload() end},
  --[[I for Information]]                      { 'i', 'System Information'},
  --[[J for ]]                                 -- { 'j', ''},
  --[[K for Karabiner]]                        { 'k', 'Karabiner-Elements'},
  --[[L for ]]                                 -- { 'l', ''},
  --[[M for Mailspring]]                       { 'm', 'Mailspring'},
  --[[N for Notion]]                           { 'n', 'Notion'},
  --[[O for OpenVPN]]                          { 'o', 'OpenVPN Connect'},
  --[[P for Preferences]]                      { 'p', 'System Preferences'},
  --[[Q for QuickTime]]                        { 'q', 'QuickTime Player'},
  --[[R for Radio]]                            { 'r', 'Spotify'},
  --[[S for Slack]]                            { 's', 'Slack'},
  --[[T for Terminal]]                         { 't', 'iTerm'},
  --[[U for Unclutter]]                        -- Set in Unclutter Preference
  --[[V for VS Code]]                          { 'v', 'Visual Studio Code'},
  --[[W for Word]]                             { 'w', 'Microsoft Word'},
  --[[X for Xcode]]                            { 'x', 'Xcode'},
  --[[Y for ]]                                 -- { 'y', ''},
  --[[Z for ]]                                 -- { 'z', ''},
}
